version: '3.8'
services:
  redis-with-exporter:
    image: peymanpn/redis-with-exporter:6.0-alpine3.15
    ports:
    - 6379:6379
    - 9121:9121
  prometheus:
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus:/etc/prometheus
  grafana-ui:
    image: grafana/grafana
    ports:
    - 3000:3000
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=secret
